### ISSUE TITLE
How to get the return value of a mockMethodCall?

### ISSUE THREAD

**Issue by JoaoCardoso193** [quavedev/testing#1]
Hi! I'm trying to test the return value of one of my Meteor Methods. I seem to be unable to figure out a way to check the return value of a method using `mockMethodCall`.

If I set the mock method call equal to a variable it returns undefined, even though my method seems to be working and returning the correct value when called normally.

I am passing the context object with a valid userId. If I try to create a callback to check the response, the mock method call won't work as the context object doesn't get recognized due to it no longer being the last argument.

I'd really appreciate any help in figuring this out. Thanks!

**Comment by JoaoCardoso193** [comment]
I noticed there was no way to do so in the current state of the package, so I added a return value to mockMethodCall and created a pull request.

**Comment by filipenevola** [comment]
Great @JoaoCardoso193, thank you!

**Comment by filipenevola** [comment]
Published quave:testing@1.0.1.
